### ISSUE TITLE
Custom Comparators

### ISSUE THREAD

**Issue by dgrnbrg** [spacejam/rust-rocksdb#10]
Hello, I'm interested in custom comparator support. I would like to be able to specify keys as lists of sorted keys. This way, I could do prefix lookups on multiple levels of variable-length prefixes. This indexing scheme is critical for building EAV database indices like [Datomic](http://www.datomic.com/)  (a functional DB) use.

**Comment by spacejam** [comment]
Added: https://github.com/spacejam/rust-rocksdb/pull/13

I'm a bit unfamiliar with the comparator, could you modify the test in comparator.rs so that it covers your desired use-case?  Bonus points for short usage example in the readme with an example of how the comparator can assist with this interesting problem.

**Comment by dgrnbrg** [comment]
Basically, I'd like to initialize the DB w/ a "serialization config", so that you can have a designated pair of K & V types with custom-defined serialization & comparator, so that it's possible to use RocksDB with crazy types. For instance, I've often wanted keys which are actually a list of many variable-length lexographically or ordinally ordered elements. For instance, a key of the form `[hostname time]` would allow one DB to answers queries about the `hostname` and about the `hostname` at a specific `time`, assuming that you sort time in reverse order (since the value at the `hostname` itself would be the latest time). But since hostname is variable length, this is trickier.

Another thing I'd like is to store multiple distinct keyspaces in the same RocksDB, in order to take advantage of the atomic writes to a single db and key multiple indices on the in sync.

I will write some code for this in a bit--I want to figure out the iterator first :)
