### ISSUE TITLE
ReadOptions are not exposed?

### ISSUE THREAD

**Issue by rschmukler** [spacejam/rust-rocksdb#113]
New to rust so apologies if this is a misfile, but it seems that `ReadOptions` only exist in `db.rs` and aren't exposed. The docs also don't reference the type (ie. http://docs.rs).

Sorry for the lack of PR - like I said, I'm not quite sure on the preferred fix / if this issue is valid.

**Comment by spacejam** [comment]
Thanks for adding this!
