### ISSUE TITLE
EXC_BAD_ACCESS with iterator

### ISSUE THREAD

**Issue by nitingupta910** [spacejam/rust-rocksdb#115]
I seem to be hitting a weird corner case: I created a DB with 10000 keys and then trying to iterate over them. Everything works when I create iterator directly in a function, however when I create a wrapper which returns DBIterator, I get EXC_BAD_ACCESS when trying to dump the db with returned iterator.

Here's a minimal demo which reproduces the issue:

`https://github.com/nitingupta910/iter_demo`
(checkout `with_upstream` branch)

Note that output stops after printing just 320 keys while 10000 keys where inserted. Running it under gdb shows EXC_BAD_ACCESS as the reason for early termination.

Uncomment call to db.iterator() in dump() and the bug **disappears**.

**Comment by nitingupta910** [comment]
Fixed the issue.

For reference, I was passing ownership of DB object to wrapper function `make_iter()` instead of reference. This was causing DB to be closed after wrapper returns, rendering the iterator invalid!

**Comment by spacejam** [comment]
hmmm maybe there's a way we could tie lifetimes into an iterator to constrain lifetimes, avoiding this problem for users in the future
