### ISSUE TITLE
Build fails on gcc 7+

### ISSUE THREAD

**Issue by yeastplume** [spacejam/rust-rocksdb#122]
It seems librocksdb-sys v0.4.1 has issues compiling its rocksdb dependency on gcc7+ with issues such as the following:
```
cargo:warning=                 from rocksdb/db/auto_roll_logger.h:15,
cargo:warning=                 from rocksdb/db/auto_roll_logger.cc:6:
cargo:warning=rocksdb/util/thread_local.h:66:16: error: ‘function’ in namespace ‘std’ does not name a template type
cargo:warning=   typedef std::function<void(void*, void*)> FoldFunc;
```
It's to be directly related to this issue, which was fixed within rocksdb:

 #https://github.com/facebook/rocksdb/issues/1492

Would suggest the rocksdb dependency needs to be updated to a newer one.

**Comment by modalduality** [comment]
In light of this, are there more specific instructions for linking together a RocksDB compilation and rust-rocksdb?

**Comment by vmx** [comment]
@spacejam This bug can be closed. I compiled master on my system where GCC 7 is the default. All tests passed.

**Comment by spacejam** [comment]
:+1:

**Comment by spacejam** [comment]
If this issue still impacts anyone using a recent version, please open a new issue!
