### ISSUE TITLE
bindgen dependency outdated

### ISSUE THREAD

**Issue by katyo** [spacejam/rust-rocksdb#191]
Please upgrade bindgen dependency in the `librocksdb-native`.

I failed to compile my app:

```
package `clang-sys v0.23.0`
    ... which is depended on by `bindgen v0.37.4`
    ... which is depended on by `libsodium-sys v0.1.0`
    ... which is depended on by `sodiumoxide v0.1.0`
    ...
links to native library `clang`

package `clang-sys v0.21.2`
    ... which is depended on by `bindgen v0.29.1`
    ... which is depended on by `librocksdb-sys v5.11.3`
    ... which is depended on by `rocksdb v0.10.0`
    ...
also links to native library `clang`
```

**Comment by jonhoo** [comment]
This is currently holding back a bunch of other crate versions transitively. The older bindgen version that is currently in use depends on things like the deprecated [`syntex` crate](https://github.com/serde-deprecated/syntex), older versions of `regex`, etc.

**Comment by jonhoo** [comment]
From this commit in a fork, it looks like moving to the newest `bindgen` shouldn't be too much pain: https://github.com/ekmartin/rust-rocksdb/commit/2e934879ff9d106ca8a0dd8cf2d677064fe1a49f

**Comment by ekmartin** [comment]
@spacejam: Could you take a quick look at #192 when you have time?
