### ISSUE TITLE
A few questions about DBResult

### ISSUE THREAD

**Issue by steveklabnik** [spacejam/rust-rocksdb#30]
Hey there,

I had a few questions about DBResult.

It's unfortunate that it's not an actual `Result`, because then you don't get the nice combinator methods. I was working on some code with @petehunt today, and I was assuming we could use `unwrap_or()`, for example, but that doesn't exist.

Is there some specific reason why it's not `DbResult<Option<T>, E>`, for example? that'd still get you the `Some`/`None` distinction, yet inherit all the goodies. I haven't spent a ton of time with this library yet though, so I might be missing something important!

**Comment by spacejam** [comment]
There is no good reason, other than my own ignorance when I was learning rust for the first time while writing this library!  I've been wanting to see this improved for a while, but haven't prioritized it.  Now that I know it's causing pain for others I'm much more incentivized to get it into a better place, and will probably have time in the next couple days to patch a few things up in this library (really also want to implement rocksdb prefix seek functionality), but if you want it asap feel free to send a PR!

**Comment by steveklabnik** [comment]
Great! I don't think it's a huge deal right this moment, but I might send you a PR tomorrow if I have some time :) you know the codebase better than I.

**Comment by petehunt** [comment]
+1 for prefix seek! :)

**Comment by steveklabnik** [comment]
Oh, and for reference: http://doc.rust-lang.org/book/error-handling.html

**Comment by spacejam** [comment]
https://github.com/spacejam/rust-rocksdb/pull/32
