### ISSUE TITLE
Should Writable take &mut references?

### ISSUE THREAD

**Issue by petehunt** [spacejam/rust-rocksdb#40]
I'm wondering if taking immutable references was intentional (since RocksDB is threadsafe) or unintentional (since you can have unintentional data races despite RocksDB being threadsafe).

I'm still a Rust newbie, but using things like `RwLock` with `rust-rocksdb` doesn't feel natural because everything takes an immutable self reference.

**Comment by spacejam** [comment]
Writable operations on the DB object itself was intentionally &self, rather than &mut self, because RocksDB handled the safety under the covers.  However, I've removed Writable because for things like WriteBatch, RocksDB does not mediate concurrent access patterns.
