### ISSUE TITLE
memory leaking-How can I see rocksdb statistics and check the memory?

### ISSUE THREAD

**Issue by Lingling7** [spacejam/rust-rocksdb#41]
I captured rocksdb memery leaking. So I want to check rocksdb statistics and `cache_index_and_filter_blocks`in rust according to the link [https://github.com/facebook/rocksdb/issues/588](https://github.com/facebook/rocksdb/issues/588)

Is there anyone who can help me with this? Thanks!

**Comment by spacejam** [comment]
I like to use valgrind for things like this! Let me know if you'd like any more info!
`valgrind --leak-check=full --show-reachable=yes /path/to/executable/that/exercises/leak/and/exits`
