### ISSUE TITLE
snapshot doesn't support Get function

### ISSUE THREAD

**Issue by siddontang** [spacejam/rust-rocksdb#42]
Hi @spacejam 

I find that snapshot has only iterator function, but I think get or getcf is very useful and important too.
If not, I have to use iterator to seek the key, call next(), and then check whether the return key matches.

Although I can wrap this in a function, iterator seek is still slower than using get in rocksdb.

**Comment by spacejam** [comment]
I agree this would be nice.  You can manually do this by calling `set_snapshot` on https://github.com/spacejam/rust-rocksdb/blob/master/src/rocksdb.rs#L777 and following what happens in https://github.com/spacejam/rust-rocksdb/blob/master/src/rocksdb.rs#L386 although I would maybe prefer that this be a method on the Snapshot struct or something.  If you can think of a nice way to do that while minimizing code duplication I would gladly accept a PR!

**Comment by siddontang** [comment]
We can extract a base get function in DB with a read option argument, so that Snapshot and DB can both use it with different read option. 

Maybe we can do it together with #43 .
