### ISSUE TITLE
why clone here?

### ISSUE THREAD

**Issue by siddontang** [spacejam/rust-rocksdb#43]
Hi @spacejam 

I notice that you use clone https://github.com/spacejam/rust-rocksdb/blob/master/src/rocksdb.rs#L441, 

But for iterator, https://github.com/spacejam/rust-rocksdb/blob/master/src/rocksdb.rs#L115 you don't use clone. 

Why they are different? or is it necessary for clone? 

Thank you.

**Comment by spacejam** [comment]
This may be a case where `clone()` was used just to satisfy the compiler, as we later pass it to `rocksdb_readoptions_destroy` which consumes it.  They are different data structures, one being the FFI pointer and the other being the rust wrapper which implements Drop for it by properly destroying it.  The code in `get_cf` is generally pretty in-need of refactoring, so if this is something that bothers you I would gladly accept a PR!  I'm a bit low on free time to tidy this up myself right now though.

**Comment by siddontang** [comment]
I guess we can create a read/write option field in DB and reuse it in get/write to avoid creating/destroying every time. 

Btw, most of time, we need caching the read item. I think we should enable filling cache in read option for DB get in default or support another get function like cache_get.
