### ISSUE TITLE
Doesn't work for me on OS X

### ISSUE THREAD

**Issue by Damienkatz** [spacejam/rust-rocksdb#59]
iMac:noise damienkatz$ cargo install rocksdb --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
       Fresh libc v0.2.12
   Compiling rocksdb v0.3.5
     Running `rustc /Users/damienkatz/.cargo/registry/src/github.com-88ac128001ac3a9a/rocksdb-0.3.5/src/main.rs --crate-name rocksdb --crate-type bin -C opt-level=3 --cfg feature=\"default\" --out-dir /Users/damienkatz/noise/target-install/release --emit=dep-info,link -L dependency=/Users/damienkatz/noise/target-install/release -L dependency=/Users/damienkatz/noise/target-install/release/deps --extern libc=/Users/damienkatz/noise/target-install/release/deps/liblibc-d9dba2869ce64308.rlib --extern rocksdb=/Users/damienkatz/noise/target-install/release/librocksdb.rlib`
error: linking with `cc` failed: exit code: 1
note: "cc" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "/Users/damienkatz/noise/target-install/release/rocksdb.0.o" "-o" "/Users/damienkatz/noise/target-install/release/rocksdb" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/damienkatz/noise/target-install/release" "-L" "/Users/damienkatz/noise/target-install/release/deps" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "/Users/damienkatz/noise/target-install/release/librocksdb.rlib" "/Users/damienkatz/noise/target-install/release/deps/liblibc-d9dba2869ce64308.rlib" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib/libstd-d16b8f0e.rlib" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib/libcollections-d16b8f0e.rlib" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib/librustc_unicode-d16b8f0e.rlib" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib/librand-d16b8f0e.rlib" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib/liballoc-d16b8f0e.rlib" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib/liballoc_jemalloc-d16b8f0e.rlib" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib/liblibc-d16b8f0e.rlib" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib/libcore-d16b8f0e.rlib" "-l" "rocksdb" "-l" "System" "-l" "pthread" "-l" "c" "-l" "m" "-l" "compiler-rt"
note: ld: library not found for -lrocksdb
clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: aborting due to previous error
error: failed to compile `rocksdb v0.3.5`, intermediate artifacts can be found at `/Users/damienkatz/noise/target-install`

Caused by:
  Could not compile `rocksdb`.

Caused by:
  Process didn't exit successfully: `rustc /Users/damienkatz/.cargo/registry/src/github.com-88ac128001ac3a9a/rocksdb-0.3.5/src/main.rs --crate-name rocksdb --crate-type bin -C opt-level=3 --cfg feature="default" --out-dir /Users/damienkatz/noise/target-install/release --emit=dep-info,link -L dependency=/Users/damienkatz/noise/target-install/release -L dependency=/Users/damienkatz/noise/target-install/release/deps --extern libc=/Users/damienkatz/noise/target-install/release/deps/liblibc-d9dba2869ce64308.rlib --extern rocksdb=/Users/damienkatz/noise/target-install/release/librocksdb.rlib` (exit code: 101)

**Comment by Damienkatz** [comment]
I've got rocksdb installed via brew.

**Comment by spacejam** [comment]
Hey @Damienkatz! rustc is not able to link this library against your copy of rocksdb. Does following the instructions in the readme for installing rocksdb work? You can tell rustc about other directories to look for shared libraries, as well. I'd maybe also try to compile one of the test rocksdb C programs, like https://github.com/facebook/rocksdb/blob/master/db/c_test.c to make sure your copy of rocksdb is usable.

**Comment by spacejam** [comment]
rocksdb is installed by default in /usr/local/lib, make sure that's in your $LD_LIBRARY_PATH!
