### ISSUE TITLE
Adding geospatial support 

### ISSUE THREAD

**Issue by soumyasd** [spacejam/rust-rocksdb#61]
Is it possible to add support for Spatial indexing from Rust. 
http://rocksdb.org/blog/2039/spatial-indexing-in-rocksdb/
https://github.com/facebook/rocksdb/blob/master/include/rocksdb/utilities/spatial_db.h

**Comment by spacejam** [comment]
If the geospatial support is present in the C API then yes! Currently away
from a computer for a few hours but I may have time to investigate and add
them if possible sometime this week!

**Comment by soumyasd** [comment]
@spacejam  - thanks. They are present in the C API as linked above.

**Comment by spacejam** [comment]
@soumyasd unfortunately I don't see the spatial functions present in the C api, which is a bit more limited than the C++ one https://github.com/facebook/rocksdb/blob/master/include/rocksdb/c.h

Maybe open a PR or issue on the upstream rocksdb repo to make them available? For the time being, Rust is unable to call into C++ libraries.
