### ISSUE TITLE
Can only store utf8 values using this crate?

### ISSUE THREAD

**Issue by andygrove** [spacejam/rust-rocksdb#63]
I can write arbitrary byte values to the rocksdb store using the put() method but when I call get() I get a DBVector for the result, and I can see it has a to_utf8() method but I can't see how to get the raw bytes (my data is not utf8).

I'm still new to Rust and I tried calling the deref() method too, but couldn't see how to get that to work.

Would appreciate some pointers.

**Comment by andygrove** [comment]
perhaps if deref() could be made public?

**Comment by spacejam** [comment]
Hey @andygrove! Traits in rust become usable when you import them, so by importing the Deref trait you should have access to the underlying slice. You can then call .to_owned() on it if you want a Vec<u8>, I believe.  Let me know if this isn't what you need, and we can improve the API!

**Comment by spacejam** [comment]
Feel free to re-open if you have outstanding issues!
