### ISSUE TITLE
Error Compiling the documentation

### ISSUE THREAD

**Issue by timlyo** [spacejam/rust-rocksdb#64]
I'm trying to build the documentation with `cargo doc` and I get the following:

`error: cannot document a package where a library and a binary have the same name. Consider renaming one or marking the target as 'doc = false'`

Adding 

```
[lib]
name = "rocksdb"

[[bin]]
name = "rocksdb_bin"
```

or 

```
[[bin]]
name = "rocksdb"
doc = false
```

to `cargo.toml` fixes this issue and allows me to compile. Would it be worth adding some form of one of the two?

**Comment by spacejam** [comment]
Feel free to nuke the binary completely! It has no purpose

**Comment by timlyo** [comment]
Ok, submitted a pull request.

**Comment by spacejam** [comment]
Thanks, @timlyo! merged
