### ISSUE TITLE
error: unresolved import `std::str::from_c_str`. There is no `from_c_str` in `std::str`

### ISSUE THREAD

**Issue by tanderberg** [spacejam/rust-rocksdb#7]
Tried compiling, got
error: unresolved import `std::str::from_c_str`. There is no `from_c_str` in `std::str`
True enough, from_c_str is deprecated. Suggested replacement here:
http://www.reddit.com/r/rust/comments/2robk4/whats_the_nondeprecated_equivalent_of_from_c_str/

**Comment by tanderberg** [comment]
Looking at the source, this problem already seems to have been fixed in master, but apparently the "official" crate has not been updated. Unfortunately, trying to use master produces another error:
src\rocksdb.rs:201:18: 201:41 error: unresolved name `slice::from_raw_mut_buf`
Is this library still being maintained?

**Comment by spacejam** [comment]
Hello @tanderberg!  I've pushed a few updates to the nightly_6.28.15 branch, but it appears that some handling of raw buffers is no longer valid, and some tests are failing.  I've been waiting a bit for rust to settle down before spending more time on this, but it seems that that now may be a good time to resume.  I'll be digging into the current buffer issues over the next couple days as I have time and I'll publish a new crate when they are ironed out!

**Comment by spacejam** [comment]
@tanderberg I've fixed the buffer issues (the way I was transmuting slices became invalid at some point) and I've pushed a new crate, 0.0.5, that should work with the current nightly.  If you have any problems at all please open an issue and I'll try to address them asap - I think I'll probably be adding support for scanning this weekend in case that's something you're interested in.  If you encounter a small semantic issue that you don't mind fixing, I'd happily accept any PR's as well.

Thanks for opening this ticket!
