### ISSUE TITLE
[Windows] Unicode path issue

### ISSUE THREAD

**Issue by kaedroho** [spacejam/rust-rocksdb#85]
On Windows, creating a database with unicode characters in the filename creates two directories: an empty one with the correct name, and one with the actual database in it but with a mangled name.

For example:
```rust
DB::open_default("_rust_rocksdb_u͔n͈̰̎i̙̮͚̦c͚̉o̼̩̰͗d͔̆̓ͥé");
```

Creates two folders:
 - ``_rust_rocksdb_u͔n͈̰̎i̙̮͚̦c͚̉o̼̩̰͗d͔̆̓ͥé`` (empty)
 - ``_rust_rocksdb_uÍ”nÌŽÍˆÌ°iÌ™Ì®ÍšÌ¦cÌ‰ÍšoÍ—Ì¼Ì©Ì°dÌ†ÍƒÍ¥Í”eÌ``  (with data inside it)

Linux works as expected (creates one folder with correct name)

**Comment by kaedroho** [comment]
https://github.com/spacejam/rust-rocksdb/blob/cff724a070b0dcf3b0fbf0a6aad32304973b7397/src/rocksdb.rs#L318-L336

Looks like the issue is the open method passes the UTF-8 string into RocksDB, Windows uses UTF-16. It's converting it into a path to create the folder before creating the database (hence the correctly named empty folder).

I'll get to work on a fix.

**Comment by kaedroho** [comment]
It looks like RocksDB uses ANSI encoded strings for filenames in Windows so unicode paths aren't possible at the moment. so I'll close this for now.

**Comment by spacejam** [comment]
Thanks for the heads up!
